# Generated by Django 4.2.2 on 2023-06-22 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
        ('trainings', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ScheduleLine',
            new_name='Training',
        ),
        migrations.RenameModel(
            old_name='ScheduleCorrection',
            new_name='TrainingCorrection',
        ),
    ]
